// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADloN6NBLA0af1gFJ-brZG77SGXkPiJEU',
    appId: '1:280223146628:web:72577c3b7e372b6e9258d1',
    messagingSenderId: '280223146628',
    projectId: 'elysian-ddd0b',
    authDomain: 'elysian-ddd0b.firebaseapp.com',
    storageBucket: 'elysian-ddd0b.firebasestorage.app',
    measurementId: 'G-Y40C74S0XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv40jhwOft45UFdP8pwz_QSQjjjgXaf88',
    appId: '1:280223146628:android:5803d9908e5e63eb9258d1',
    messagingSenderId: '280223146628',
    projectId: 'elysian-ddd0b',
    storageBucket: 'elysian-ddd0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9zMF8lyaFmde4GtiJrE6LMyLxioly2k',
    appId: '1:280223146628:ios:695f342ab331c36d9258d1',
    messagingSenderId: '280223146628',
    projectId: 'elysian-ddd0b',
    storageBucket: 'elysian-ddd0b.firebasestorage.app',
    iosBundleId: 'com.example.elysianUser',
  );
}
